# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 备忘录
email: shenmimu@163.com
description: > # this means to ignore newlines until "baseurl:"
  愚者千虑，或有一得。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shenmimoon.github.io" # the base hostname & protocol for your site
twitter_username: shenmimoon
github_username:  shenmimoon

# Build settings
future: true
incremental: true
